### ISSUE TITLE
docker-compose.yaml 填写问题

### ISSUE THREAD

**Issue by fangyuan99** [paradox8599/mirai-chatgpt-setup#3]
`docker-compose.yaml` 这个文件不知道咋填写啊，是在原项目的基础上填写:
```
version: '3.4'
services:
  mirai:
    image: ttionya/mirai-http:latest
    restart: always
    environment:
      LANG: 'C.UTF-8'
    volumes:
      - ./mirai/bots:/mirai/bots
      - ./mirai/config:/mirai/config
      - ./mirai/data:/mirai/data
      - ./mirai/plugin-libraries:/mirai/plugin-libraries
      - ./mirai/libs:/mirai/libs
      # - ./mirai/config.json:/mirai/config.json # 如果你要修改 mcl 的设置，就解除这个注释
  chatgpt:
    image: lss233/chatgpt-mirai-qq-bot:latest
    restart: always
    environment:
      LANG: 'C.UTF-8'
      XPRA_PASSWORD: 'lss233' # XPRA 密码，建议修改
    ports:
      - 14500:14500
    volumes:
      - ./config.json:/app/config.json
      # - ./fonts:/app/fonts # 如果你想自定义字体，就解除注释
QQ:*******
...
```
这样么？
